In [12]:
import random
import numpy as np


POLYNOMIAL BASIS

In [1]:
def MakeGen(m, b, c, d, k):
    res=[0]*(m+1)
    res[m]=res[b]=res[c]=res[d]=res[k]=1
    return res[::-1]

In [2]:
def MakeX(poly):
    x=[]
    for i in range(m-1):
        if poly[i]==1:
            t = f'x^{m-1-i}'
            x.append(t)
    if poly[-1]==1: x.append('1')
    if x==[]: x==[0]*m
    return x
       
def PrintX(poly):
    pol=MakeX(poly)
    res=[]
    res.append(' + '.join(pol))
    return res


In [3]:
def AddPoly(a, b):
    c=[0]
    for i in range(m):
        c.append(((a[i] if i<len(a) else 0)+(b[i] if i<len(b) else 0))%2)
    return (c if len(c)<=m else c[(len(c)-m):])
        

In [4]:
def PolyMod(a, g):
    final=np.polydiv(a, g)[1]
    for i in range (0, len(final)+1):
        final[i]=final[i]%2
    return np.array(final)

def MulPoly(a, b):
    p1 = np.poly1d(a)
    p2 = np.poly1d(b)
    res=p1*p2 
    for i in range (0, len(res)+1):
        res[i]=res[i]%2
    return PolyMod(res, GEN)


In [5]:
def SquarePoly(a):
    res=a
    i=1
    while i<len(res):
        if i%2==1:
            res.insert(i, 0)
        i=i+1
    return PolyMod(np.poly1d(res), GEN)

In [6]:
def Trace(a):
    res=0
    deg=0
    while deg<m:
        res=res+ int(Convert(PowPoly(a, ((2**deg)%(2**m - 1)))), 2)
        deg=deg+1
        print(deg)
    return res%2

In [7]:
def PowPoly(a, n):
    if n==0: return [1]
    elif n%2==0:
        return PowPoly(MulPoly(a, a), n//2)
    else:
        return MulPoly(PowPoly(MulPoly(a, a), n//2), a)

In [8]:
def Reverse(a):
    return PowPoly(a, 2**m-2)

In [9]:
def Convert(a):
    res=[0]*(len(a))
    for i in range(len(a)):
        res[i]=str(int(a[i]))
    result=''.join(res)
    return result


In [10]:
def Deconvert(a):
    return list(map(int, a))

In [13]:
print('Enter the m - the field dimension:')
m=int(input('dimension: '))
print('Choose to what degrees the coefficients are equal to 1 (start from the biggest):')
k, k1, k2, k3 = int(input('degrees: ')), int(input()), int(input()), int(input())
GEN = np.poly1d(MakeGen(m, k, k1, k2, k3))
print(GEN, ' - field generator ')

Enter the m - the field dimension:
dimension: 283
Choose to what degrees the coefficients are equal to 1 (start from the biggest):
degrees: 26
9
1
0
   283     26     9
1 x   + 1 x  + 1 x + 1 x + 1  - field generator 


In [17]:
print('Enter 1 if you wants randomly generate inputs data or enter 2 to fill in it by yourself: ')
choise=input()
if choise=='1':
    items = [1, 0]
    Poly_one = random.choices(items, k=m)
    Poly_two = random.choices(items, k=m)
    Poly_one_copy=Poly_one.copy()
    Poly_two_copy=Poly_two.copy()
    print('A = ', PrintX(Poly_one))
    print('B = ', PrintX(Poly_two))
    print('A = ', hex(int(Convert(Poly_one), 2))[2:].swapcase())
    print('B = ', hex(int(Convert(Poly_two), 2))[2:].swapcase())
    print('A + B = ', hex(int(Convert(AddPoly(Poly_one, Poly_two)), 2))[2:].swapcase())
    print('A*B = ', hex(int(Convert(MulPoly(Poly_one, Poly_two)), 2))[2:].swapcase())
    print('A^2 = ', hex(int(Convert(SquarePoly(Poly_one)), 2))[2:].swapcase())
    print('Enter the degree you want the polynom to raise in: ')
    n=int(input('n in dec = '))
    k=hex(n)[2:].swapcase()
    print('n in hex = ', k)
    print(f'A^{k} = ', hex(int(Convert(PowPoly(Poly_one_copy, n)), 2))[2:].swapcase())
    #print('Tr(A) = ', Trace(Poly_one_copy))
    #print('Tr(A) = ', hex(int(Convert(Trace(Poly_one_copy)), 2))[2:].swapcase())
    print('A^-1 = ', hex(int(Convert(Reverse(Poly_one_copy)), 2))[2:].swapcase())
    print('Сorrectness tests:')
    print(f'A^(2^{m}-1) = ', hex(int(Convert(PowPoly(Poly_one_copy, 2**m-1)), 2))[2:].swapcase())


if choise=='2':
    Poly_1 = input('Enter first polynom: A = ')
    Poly_one = Deconvert(str(bin(int(f'0x{Poly_1.swapcase()}', 16)))[2:])
    while len(Poly_one)<m: Poly_one.insert(0, 0)
    Poly_2 = input('Enter second polynom: B = ')
    Poly_two = Deconvert(bin(int(f'0x{Poly_2.swapcase()}', 16))[2:])
    while len(Poly_two)<m: Poly_two.insert(0, 0)
    print('A = ', PrintX(Poly_one))
    print('B = ', PrintX(Poly_two))
    print('A + B = ', hex(int(Convert(AddPoly(Poly_one, Poly_two)), 2))[2:].swapcase())
    print('A*B = ', hex(int(Convert(MulPoly(Poly_one, Poly_two)), 2))[2:].swapcase())
    print('A^2 = ', hex(int(Convert(SquarePoly(Poly_one)), 2))[2:].swapcase())
    Poly_one= Deconvert(bin(int(f'0x{Poly_1.swapcase()}', 16))[2:])
    print('Enter the degree you want the polynom to raise in: ')
    n=int(input('n in dec = '))
    k=hex(n)[2:].swapcase()
    print('n in hex = ', k)
    Poly_one= Deconvert(bin(int(f'0x{Poly_1.swapcase()}', 16))[2:])
    Poly_two= Deconvert(bin(int(f'0x{Poly_2.swapcase()}', 16))[2:])
    print(f'A^{k} = ', hex(int(Convert(PowPoly(Poly_one, n)), 2))[2:].swapcase())
    #print('Tr(A) = ', Trace(Poly_one_copy))
    print('A^-1 = ', hex(int(Convert(Reverse(Poly_one)), 2))[2:].swapcase())
    print('Сorrectness tests:')
    print(f'A^(2^{m}-1) = ', hex(int(Convert(PowPoly(Poly_one, 2**m-1)), 2))[2:].swapcase())

Enter 1 if you wants randomly generate inputs data or enter 2 to fill in it by yourself: 
1
A =  ['x^282 + x^281 + x^277 + x^276 + x^275 + x^272 + x^271 + x^270 + x^268 + x^267 + x^260 + x^259 + x^256 + x^254 + x^251 + x^250 + x^249 + x^248 + x^246 + x^245 + x^243 + x^239 + x^238 + x^236 + x^233 + x^232 + x^230 + x^228 + x^226 + x^223 + x^217 + x^216 + x^214 + x^213 + x^212 + x^210 + x^207 + x^206 + x^205 + x^204 + x^202 + x^201 + x^200 + x^199 + x^198 + x^197 + x^196 + x^195 + x^194 + x^193 + x^192 + x^189 + x^187 + x^185 + x^181 + x^180 + x^177 + x^175 + x^174 + x^173 + x^171 + x^170 + x^169 + x^168 + x^167 + x^163 + x^162 + x^161 + x^160 + x^159 + x^157 + x^155 + x^154 + x^153 + x^152 + x^149 + x^148 + x^143 + x^140 + x^138 + x^137 + x^136 + x^131 + x^129 + x^128 + x^127 + x^124 + x^120 + x^119 + x^115 + x^114 + x^113 + x^112 + x^111 + x^107 + x^103 + x^102 + x^100 + x^98 + x^93 + x^91 + x^90 + x^89 + x^87 + x^85 + x^83 + x^81 + x^80 + x^78 + x^73 + x^72 + x^71 + x^68 + x^67 + x^66 


NORMAL BASIS


In [16]:
def MakeBasis(m):
    x=[]
    for i in range(m):
        t = f'x^{2**i}'
        x.append(t)
    res=[]
    res.append(', '.join(x))
    return res
#print('Basis: ', MakeBasis(m))

In [18]:
def Trace(a):
    res=0
    for i in range(len(a)):
        res=res+a[i]
    return res%2

In [19]:
def SquarePoly(a):
    return a[-1:] + a[:-1]


In [20]:
def MakeMatrix(m):
    p=2*m+1
    matrix = np.zeros((m, m))
    for i in range(len(matrix[0])):
        for j in range(len(matrix)):
            if (2**i+2**j)%p==1 or (2**i-2**j)%p==1 or (-2**i+2**j)%p==1 or (-2**i-2**j)%p==1:
                matrix[:,i][j] = 1
    return matrix


In [21]:
def MulPoly(a, b):
    while len(a)>m: del a[0]
    while len(b)>m: del b[0]
    if a==[1]: return b
    res=m*[0]
    M=MakeMatrix(m)
    for i in range(m):
        res[i]=np.array(np.array(a[i:] + a[:i]).dot(M))
        for j in range(len(res[i])):
            res[i][j]=res[i][j]%2
        res[i]=int(res[i].dot(np.array([b[i:]+b[:i]]).transpose()))%2
    return (res)


In [22]:
def ItohTsujiiReverse(a):
    x=bin(m-1)[2:]
    t=len(x)-1
    beta=a
    k=1
    for i in reversed(range(0, t)):
        beta=MulPoly(PowPoly(beta, 2**k), beta)
        k=2*k
        if x[::-1][i]=='1':
            beta=MulPoly(SquarePoly(beta), a)
            k=k+1
    beta=SquarePoly(beta)
    return beta


In [22]:
def PowPoly(a, n):
    if n==0: return [1]
    elif n%2==0:
        return PowPoly(SquarePoly(a), n//2)
    else:
        return MulPoly(PowPoly(SquarePoly(a), n//2), a)
        

possible input for dimension 179:

A = '5DFD6057D4966CE794CE3E061E22AFC373A964CE3ECC6'

B = '7324FC676C83A2477A247F76C197A247ED94C9627A247'

C = '4B9BE2B966CE794CE347ED94C9627AE061EA39512BF77'

In [33]:
print('Enter the m - the field dimension:')
m=int(input('dimension: '))
print('Enter 1 if you wants randomly generate inputs data or enter 2 to fill in it by yourself: ')
choise=input()
if choise=='1':
    items = [1, 0]
    AA = random.choices(items, k=m)
    BB = random.choices(items, k=m)
    print('A = ', hex(int(Convert(AA), 2))[2:].swapcase())
    print('B = ', hex(int(Convert(BB), 2))[2:].swapcase())
    print('Λ = ', MakeMatrix(m))
    print('A + B = ', hex(int(Convert(AddPoly(AA, BB)), 2))[2:].swapcase())
    print('A^2 = ', hex(int(Convert(SquarePoly(AA)), 2))[2:].swapcase())
    print('A*B = ', hex(int(Convert(MulPoly(AA, BB)), 2))[2:].swapcase())
    print('Tr(A) = ', Trace(AA))
    n=int(input('n in dec = '))
    k=hex(n)[2:].swapcase()
    print('n in hex =', k)
    print(f'A^{k} = ', hex(int(Convert(PowPoly(AA, n)), 2))[2:].swapcase())
    print('A^-1 by Itoh Tsujii algorithm = ', hex(int(Convert(ItohTsujiiReverse(AA)), 2))[2:].swapcase())
    print('A^-1 = ', hex(int(Convert(PowPoly(AA, 2**m-2)), 2))[2:].swapcase())
    print('Сorrectness tests:')
    C = Convert(PowPoly(AA, 2**m-1))
    if ('0' in C) is False:
        print(f'A^(2^{m}-1) = ' + '1')
    else: print('ERROR')
    print('(A+B)^2 = ', hex(int(Convert(SquarePoly(AddPoly(AA, BB))), 2))[2:].swapcase())
    print('A^2 + B^2 = ', hex(int(Convert(AddPoly(SquarePoly(AA), SquarePoly(BB))), 2))[2:].swapcase())
    print('(A+B)*C = ', hex(int(Convert(MulPoly(AddPoly(AA, BB), CC)), 2))[2:].swapcase())
    print('A*C + B*C = ', hex(int(Convert(AddPoly(MulPoly(AA, CC), MulPoly(CC, BB))), 2))[2:].swapcase())
if choise=='2':
    Poly_1 = input('Enter first polynom: A = ')
    AA = Deconvert(str(bin(int(f'0x{Poly_1.swapcase()}', 16)))[2:])
    Poly_2 = input('Enter second polynom: B = ')
    BB = Deconvert(str(bin(int(f'0x{Poly_2.swapcase()}', 16)))[2:])
    print('Λ = ', MakeMatrix(m))
    print('A + B = ', hex(int(Convert(AddPoly(AA, BB)), 2))[2:].swapcase())
    print('A^2 = ', hex(int(Convert(SquarePoly(AA)), 2))[2:].swapcase())
    print('A*B = ', hex(int(Convert(MulPoly(AA, BB)), 2))[2:].swapcase())
    print('Tr(A) = ', Trace(AA))
    n=int(input('n in dec = '))
    k=hex(n)[2:].swapcase()
    print('n in hex = ', k)
    print(f'A^{k} = ', hex(int(Convert(PowPoly(AA, n)), 2))[2:].swapcase())
    print('A^-1 by Itoh Tsujii algorithm = ', hex(int(Convert(ItohTsujiiReverse(AA)), 2))[2:].swapcase())
    print('A^-1 = ', hex(int(Convert(PowPoly(AA, 2**m-2)), 2))[2:].swapcase())
    print('Сorrectness tests:')
    C = Convert(PowPoly(AA, 2**m-1))
    if ('0' in C) is False:
        print(f'A^(2^{m}-1) = ' + '1')
    else: print('ERROR')
    print('(A+B)^2 = ', hex(int(Convert(SquarePoly(AddPoly(AA, BB))), 2))[2:].swapcase())
    print('A^2 + B^2 = ', hex(int(Convert(AddPoly(SquarePoly(AA), SquarePoly(BB))), 2))[2:].swapcase())
    print('(A+B)*C = ', hex(int(Convert(MulPoly(AddPoly(AA, BB), CC)), 2))[2:].swapcase())
    print('A*C + B*C = ', hex(int(Convert(AddPoly(MulPoly(AA, CC), MulPoly(CC, BB))), 2))[2:].swapcase())
    

Enter the m - the field dimension:
dimension: 179
Enter 1 if you wants randomly generate inputs data or enter 2 to fill in it by yourself: 
1
A =  2E6470881DA0B0DDFF4B180E98DC237FA01B0C6F56DC4
B =  493EF5BC448ABD4C18D7F4E5624EF8A33882EBBF9BBED
Λ =  [[0. 1. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
A + B =  675A8534592A0D91E79CECEBFA92DBDC9899E7D0CD629
A^2 =  173238440ED0586EFFA58C074C6E11BFD00D8637AB6E2
A*B =  61B8DC9593CBE1A72413E4BD7E867D979B9E1DC47ADBC
Tr(A) =  0
n in dec = 675432134567898765432456789
n in hex = 22EB451621CCB6BE5540655
A^22EB451621CCB6BE5540655 =  334539ECA1411EAD5643FC90CF817AC52800A5344E5B7
A^-1 by Itoh Tsujii algorithm =  744BD55F1AE0B93BE6EF3CE1098C41C6507B23A8810B4
A^-1 =  744BD55F1AE0B93BE6EF3CE1098C41C6507B23A8810B4
Сorrectness tests:
A^(2^179-1) = 1
(A+B)^2 =  73AD429A2C9506C8F3CE7675FD496DEE4C4CF3E866B14
A^2 + B^2 =  73AD429A2C9506C8F3CE7675FD496DEE4C4C

In [199]:
%timeit AddPoly(AA, BB)
%timeit MulPoly(AA, BB)
%timeit SquarePoly(AA)
%timeit PowPoly(AA, 1000)
%timeit ItohTsujiiReverse(AA)
%timeit Trace(AA)

43.3 µs ± 3.15 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
127 ms ± 4.39 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
1.02 µs ± 14.2 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
618 ms ± 29.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
974 ms ± 33.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
6.87 µs ± 381 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [ ]:
Poly_1 = '606FAF45730E14EF7CDA682987DAD34D0C6CBB15A68C21880E28D4E6F5A12EFCD1D9259'
Poly_2 = '5A7BFFEB7873DC3CF75FAF48C5329870DC64FCFCD1D960C64D43DA26EFD0C3CF78CD874'
Poly_one = Deconvert(str(bin(int(f'0x{Poly_1.swapcase()}', 16)))[2:])
Poly_two = Deconvert(bin(int(f'0x{Poly_2.swapcase()}', 16))[2:])
%timeit AddPoly(Poly_one, Poly_two)
%timeit MulPoly(Poly_one, Poly_two)
%timeit SquarePoly(Poly_one)
Poly_one = Deconvert(str(bin(int(f'0x{Poly_1.swapcase()}', 16)))[2:])
Poly_two = Deconvert(bin(int(f'0x{Poly_2.swapcase()}', 16))[2:])
%timeit PowPoly(Poly_one, 1000)
%timeit Reverse(Poly_one)
%time Trace(Poly_one)